#!/bin/bash

args=$#
path=$HOME/$1

if (( args > 0 )); then
	if [[ -f $path ]]; then
		sed -i "1cset \$wallpaper $path" $HOME/.config/sway/wallpaper.sh
	else
		echo "Argument passed is not a valid path."
	fi
else
	echo "Expected 1 argument, received $args."
fi

swaymsg reload
